/**
 * Starter catalog.
 *
 * Every row here is a *standing* benefit that the program documents publicly on
 * its own site, and each carries the source_url it came from. Time-limited
 * merchant promotions deliberately are NOT seeded: they live behind member
 * logins and mobile apps, they change weekly, and inventing plausible-looking
 * ones would be worse than an empty feed. Those come from members through the
 * quick-add form.
 *
 * Seed rows are global (group_id NULL) and authorless (created_by NULL), which
 * is what distinguishes them from member contributions. `seed_key` is their
 * stable identity for upserts.
 *
 * verified_at is deliberately left NULL: these were read off public marketing
 * pages, not confirmed inside a member account. The first member to check one
 * can stamp it.
 */
import type { OfferCategory, Shareability } from "../../lib/types";

export interface SeedOffer {
  seed_key: string;
  program_slug: string;
  title_he: string;
  merchant: string;
  category: OfferCategory;
  discount_text: string;
  description_he: string | null;
  shareability: Shareability;
  /** Redeeming it spends one of the holder's capped monthly entitlements. */
  costs_quota?: boolean;
  source_url: string;
}

export const OFFERS: SeedOffer[] = [
  // ---------------------------------------------------------------- לאומי בונוס
  {
    seed_key: "leumi-bonus-food-vouchers",
    program_slug: "leumi-bonus",
    title_he: "תווי בונוס לרשתות מזון ופארם",
    merchant: "רשתות מזון ופארם",
    category: "food",
    discount_text: "עד 20% חזרה מהבנק",
    description_he:
      "רוכשים תו בסכום שבוחרים, והבנק מחזיר חלק מהסכום לחשבון. את התו עצמו אפשר להעביר.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/category/1329",
  },
  {
    seed_key: "leumi-bonus-checkout-discounts",
    program_slug: "leumi-bonus",
    title_he: "הנחות קבועות במעמד החיוב",
    merchant: "רשתות ובתי עסק מובילים",
    category: "other",
    discount_text: "הנחה אוטומטית בחיוב",
    description_he:
      "ההנחה נכנסת אוטומטית כשמשלמים בכרטיס לאומי, ולכן צריך שבעל הכרטיס יהיה זה שמשלם.",
    shareability: "presence_required",
    source_url: "https://www.leumi.co.il/he/bonus",
  },
  {
    seed_key: "leumi-bonus-fx-fee",
    program_slug: "leumi-bonus",
    title_he: "עמלת עסקאות מט״ח מוזלת",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "1.5% בלבד",
    description_he: "תנאי של הכרטיס עצמו — חל רק על העסקאות של בעל הכרטיס.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/he/credit-cards",
  },
  {
    seed_key: "leumi-bonus-shopping-vouchers",
    program_slug: "leumi-bonus",
    title_he: "תווי קנייה למותגים ורשתות",
    merchant: "מותגי אופנה, חשמל ובית",
    category: "fashion",
    discount_text: "תווי קנייה בהנחה",
    description_he: "תו קנייה שנרכש דרך המועדון ניתן להעברה למי שישתמש בו.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/",
  },
  {
    seed_key: "leumi-bonus-leisure",
    program_slug: "leumi-bonus",
    title_he: "מבלים ונהנים — מסעדות, מופעים ואטרקציות",
    merchant: "מסעדות, מופעים ואטרקציות",
    category: "culture",
    discount_text: "מחירים מוזלים למחזיקי הכרטיס",
    description_he: "קטגוריית הפנאי של לאומי בונוס: הצגות, אטרקציות למשפחה ומסעדות.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/category/1349",
  },
  {
    seed_key: "leumi-bonus-servicemen",
    program_slug: "leumi-bonus",
    title_he: "הטבות למשרתים",
    merchant: "בנק לאומי",
    category: "other",
    discount_text: "מסלול הטבות ייעודי",
    description_he: "קטגוריית הטבות ייעודית למשרתי מילואים ומשרתי כוחות הביטחון.",
    shareability: "presence_required",
    source_url: "https://bonus.leumi.co.il/category/1627",
  },
  {
    seed_key: "leumi-bonus-new-account",
    program_slug: "leumi-bonus",
    title_he: "הטבות פתיחת חשבון",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "מסלול הטבות למצטרפים",
    description_he: "רלוונטי למי שפותח חשבון בעצמו — לא ניתן להעברה.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/open-account/",
  },

  // --------------------------------------------------------- מועדון צרכנות HOT
  {
    seed_key: "hot-14k-businesses",
    program_slug: "hot-club",
    title_he: "הנחות בכ-14,000 בתי עסק",
    merchant: "רשתות ובתי עסק בכל הארץ",
    category: "other",
    discount_text: "הנחה במעמד החיוב",
    description_he:
      "ההנחה מוצמדת לכרטיס המועדון, ולכן החבר עצמו צריך לשלם או להיות בקופה.",
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-digital-wallet",
    program_slug: "hot-club",
    title_he: "ארנק דיגיטלי — שוברים למותגים",
    merchant: "מותגי אופנה, בית, ספורט וטיפוח",
    category: "fashion",
    discount_text: "עד 20% הנחה",
    description_he:
      "שוברים דיגיטליים למותגים, כלי בית, צעצועים, ריהוט, מסעדות ובתי קפה. השובר עובר בקלות.",
    shareability: "transferable",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-supermarkets",
    program_slug: "hot-club",
    title_he: "הנחות ברשתות המזון",
    merchant: "רשתות מזון",
    category: "food",
    discount_text: "הנחה קבועה בקופה",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-travel",
    program_slug: "hot-club",
    title_he: "הטבות תיירות ונופש",
    merchant: "חברות תיירות ומלונות",
    category: "travel",
    discount_text: "מחירי מועדון",
    description_he: "הזמנה שמבצע החבר עבור מי שנוסע — לרוב ניתנת להעברה.",
    shareability: "transferable",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-electronics",
    program_slug: "hot-club",
    title_he: "הנחות בחשמל ומוצרים לבית",
    merchant: "רשתות חשמל ומוצרי בית",
    category: "electronics",
    discount_text: "הנחת מועדון",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-card-fee-waiver",
    program_slug: "hot-club",
    title_he: "פטור מדמי כרטיס אשראי",
    merchant: "מועדון הוט",
    category: "finance",
    discount_text: "ללא דמי כרטיס",
    description_he: "תנאי של הכרטיס האישי — לא רלוונטי לאף אחד אחר.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/hot_consumer_card/",
  },
  {
    seed_key: "hot-loan",
    program_slug: "hot-club",
    title_he: "הלוואה לכל מטרה בתנאי מועדון",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "עד 160,000 ₪",
    description_he: "הלוואה בתנאים מיוחדים לחברי מועדון הוט. אישית לחלוטין.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/hot_consumer_card/",
  },
  {
    seed_key: "hot-insurance",
    program_slug: "hot-club",
    title_he: "הטבות בביטוח ובפיננסים",
    merchant: "חברות ביטוח ופיננסים",
    category: "finance",
    discount_text: "תנאי מועדון",
    description_he: null,
    shareability: "personal_only",
    source_url: "https://www.hot.co.il/",
  },

  // ------------------------------------------------------------------ פיס פלוס
  // Venue-level offers gathered from public Pais Plus listings and published
  // roundups. Prices marked as seasonal carry that note in description_he:
  // they were published for a specific summer campaign and need re-checking.
  // Nearly all of these consume one of the subscriber's monthly entitlements.
  {
    seed_key: "pais-cinema-ticket",
    program_slug: "pais-plus",
    title_he: "כרטיס לסרט ברשתות הקולנוע",
    merchant: "סינמה סיטי, פלאנט, הוט סינמה, מובילנד",
    category: "culture",
    discount_text: "9 ₪ בימי חמישי · 20 ₪ בשאר הימים",
    description_he: "ההטבה הכי מוכרת של פיס פלוס. המנוי מזמין ומעביר את הכרטיס.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/product/2738",
  },
  {
    seed_key: "pais-cinema-vip",
    program_slug: "pais-plus",
    title_he: "סינמה סיטי — זוג כרטיסים למתחם VIP",
    merchant: "סינמה סיטי",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/product/96",
  },
  {
    seed_key: "pais-usplash",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק מים",
    merchant: "U Splash אילת",
    category: "travel",
    discount_text: "65 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-waterland",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק מים",
    merchant: "Waterland אילת",
    category: "travel",
    discount_text: "95 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-hofgai",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק מים",
    merchant: "חוף גיא, כנרת",
    category: "travel",
    discount_text: "57 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-yamit2000",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק מים",
    merchant: "ימית 2000, חולון",
    category: "travel",
    discount_text: "87 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-hamatgader",
    program_slug: "pais-plus",
    title_he: "כניסה לחמי מרפא",
    merchant: "חמת גדר",
    category: "travel",
    discount_text: "מ-85 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-eretzisrael",
    program_slug: "pais-plus",
    title_he: "כניסה למוזיאון",
    merchant: "מוזיאון ארץ ישראל, תל אביב",
    category: "culture",
    discount_text: "30 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-childrens",
    program_slug: "pais-plus",
    title_he: "כניסה למוזיאון הילדים",
    merchant: "המוזיאון הישראלי לילדים, חולון",
    category: "culture",
    discount_text: "42 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-bloomfield",
    program_slug: "pais-plus",
    title_he: "כניסה למוזיאון המדע",
    merchant: "מוזיאון המדע בלומפילד, ירושלים",
    category: "culture",
    discount_text: "42 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-madatech",
    program_slug: "pais-plus",
    title_he: "כניסה למדעטק",
    merchant: "מדעטק, חיפה",
    category: "culture",
    discount_text: "36 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-hadassah",
    program_slug: "pais-plus",
    title_he: "כניסה למוזיאון הרפואה",
    merchant: "מוזיאון הרפואה הדסה, חדרה",
    category: "culture",
    discount_text: "37 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-agmon",
    program_slug: "pais-plus",
    title_he: "כניסה לאגמון החולה",
    merchant: "אגמון החולה",
    category: "culture",
    discount_text: "מ-10 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-redsea-sports",
    program_slug: "pais-plus",
    title_he: "פעילות ימית",
    merchant: "רד סי ספורטס, אילת",
    category: "travel",
    discount_text: "מ-52 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-aquasport",
    program_slug: "pais-plus",
    title_he: "צלילה",
    merchant: "אקווה ספורט, אילת",
    category: "travel",
    discount_text: "מ-113 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-top94",
    program_slug: "pais-plus",
    title_he: "פארק אתגרים",
    merchant: "טופ 94, אילת",
    category: "travel",
    discount_text: "מ-15 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-selfie-museum",
    program_slug: "pais-plus",
    title_he: "כניסה למוזיאון הסלפי",
    merchant: "מוזיאון הסלפי, אילת",
    category: "travel",
    discount_text: "מ-85 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-kayak-blum",
    program_slug: "pais-plus",
    title_he: "שייט קיאקים",
    merchant: "קיאקי כפר בלום",
    category: "travel",
    discount_text: "62 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-rafting-jordan",
    program_slug: "pais-plus",
    title_he: "רפטינג",
    merchant: "רפטינג נהר הירדן",
    category: "travel",
    discount_text: "מ-46 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-indypark",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק",
    merchant: "אינדי פארק",
    category: "travel",
    discount_text: "76 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-galiyam",
    program_slug: "pais-plus",
    title_he: "כניסה לחוף",
    merchant: "גלי ים, חוף אכזיב",
    category: "travel",
    discount_text: "מ-65 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-meianot",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק",
    merchant: "פארק מי ענות",
    category: "travel",
    discount_text: "מ-31 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-safari",
    program_slug: "pais-plus",
    title_he: "כניסה לספארי",
    merchant: "ספארי רמת גן",
    category: "culture",
    discount_text: "60 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-ganguru",
    program_slug: "pais-plus",
    title_he: "כניסה לגן גורו",
    merchant: "גן גורו",
    category: "culture",
    discount_text: "41 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-haikeif",
    program_slug: "pais-plus",
    title_he: "כניסה לחי כיף",
    merchant: "חי כיף, ראשון לציון",
    category: "culture",
    discount_text: "20 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-haipark",
    program_slug: "pais-plus",
    title_he: "כניסה לחי פארק",
    merchant: "חי פארק, קרית מוצקין",
    category: "culture",
    discount_text: "מ-28 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-ninjacity",
    program_slug: "pais-plus",
    title_he: "כניסה לנינג׳ה סיטי",
    merchant: "נינג׳ה סיטי",
    category: "culture",
    discount_text: "45 ₪ לשעתיים",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-gravity",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק טרמפולינות",
    merchant: "גרביטי פארק",
    category: "culture",
    discount_text: "מ-35 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-funkymonkey",
    program_slug: "pais-plus",
    title_he: "כניסה למתחם משחקים",
    merchant: "פאנקי מאנקי",
    category: "culture",
    discount_text: "מ-22 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-ijump",
    program_slug: "pais-plus",
    title_he: "כניסה לפארק קפיצות",
    merchant: "I Jump",
    category: "culture",
    discount_text: "מ-15 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-kfitzuba",
    program_slug: "pais-plus",
    title_he: "כניסה למתחם משחקים",
    merchant: "קפיצובה",
    category: "culture",
    discount_text: "מ-34 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-paelton",
    program_slug: "pais-plus",
    title_he: "כניסה למתחם משחקים",
    merchant: "פעלטון",
    category: "culture",
    discount_text: "מ-17 ₪",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-dominos",
    program_slug: "pais-plus",
    title_he: "פריט חינם בקניית 2 פיצות משפחתיות",
    merchant: "דומינוס פיצה",
    category: "food",
    discount_text: "פריט חינם",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-pizzahut",
    program_slug: "pais-plus",
    title_he: "שדרוג פיצה משפחתית ל-XL",
    merchant: "פיצה האט",
    category: "food",
    discount_text: "שדרוג ללא תשלום",
    description_he: "מחיר שפורסם במבצע הקיץ של פיס פלוס — כדאי לאמת מחיר עדכני לפני שמבקשים.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-ramilevy",
    program_slug: "pais-plus",
    title_he: "הנחות על קניות מזון",
    merchant: "רמי לוי",
    category: "food",
    discount_text: "עד 10% הנחה",
    description_he: "הטבת מזון קבועה למנויי הפיס. מנוצלת מתוך מכסת הטבות המזון החודשית.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://www.mako.co.il/finances-consumer/Article-8406230a1953791026.htm",
  },
  {
    seed_key: "pais-roladin",
    program_slug: "pais-plus",
    title_he: "הנחה לחברי מועדון",
    merchant: "רולדין",
    category: "food",
    discount_text: "הנחת מנויים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-theatre",
    program_slug: "pais-plus",
    title_he: "כרטיסים להצגות",
    merchant: "תיאטראות והיכלי תרבות",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: "המנוי מזמין דרך החשבון שלו ומעביר את הכרטיס — ההטבה הכי נוחה לשיתוף.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/category/291",
  },
  {
    seed_key: "pais-shows",
    program_slug: "pais-plus",
    title_he: "מופעי מוסיקה והופעות",
    merchant: "אולמות ואמפיתיאטרונים",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/category/282",
  },
  {
    seed_key: "pais-vacations",
    program_slug: "pais-plus",
    title_he: "חופשות בארץ ובחו״ל",
    merchant: "מלונות ואתרי נופש",
    category: "travel",
    discount_text: "מחירי מנויים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/category/263",
  },
  {
    seed_key: "pais-beauty",
    program_slug: "pais-plus",
    title_he: "טיפוח ויופי",
    merchant: "מכוני טיפוח וספא",
    category: "health",
    discount_text: "מחירי מנויים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/category/344",
  },
  {
    seed_key: "pais-deals",
    program_slug: "pais-plus",
    title_he: "מבצעים והנחות",
    merchant: "בתי עסק משתתפים",
    category: "other",
    discount_text: "מבצעים מתחלפים",
    description_he: null,
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://paisplus.co.il/category/271",
  },
  {
    seed_key: "pais-live-festival",
    program_slug: "pais-plus",
    title_he: "פסטיבל פיס LIVE",
    merchant: "מפעל הפיס",
    category: "culture",
    discount_text: "בלעדי למנויי הפיס",
    description_he: "פסטיבל שמיועד למנויים בלבד.",
    shareability: "transferable",
    costs_quota: true,
    source_url: "https://www.pais.co.il/info/paisplus.aspx",
  },
  {
    seed_key: "pais-vip",
    program_slug: "pais-plus",
    title_he: "הטבות VIP לזהב פלוס ופלטינום",
    merchant: "מפעל הפיס",
    category: "other",
    discount_text: "הטבות בלעדיות לפי דרגה",
    description_he: "תלוי בדרגת המנוי עצמו: בעל שני כרטיסים מקבל מעמד זהב פלוס ושתי הטבות VIP.",
    shareability: "personal_only",
    source_url: "https://www.pais.co.il/info/default.aspx?PageId=1178",
  },
  {
    seed_key: "pais-monthly-quota",
    program_slug: "pais-plus",
    title_he: "מכסת זכאויות חודשית",
    merchant: "מפעל הפיס",
    category: "other",
    discount_text: "12 זכאויות בכסף · 18 בפלטינום",
    description_he: "כסף: 3 מזון, 6 סרטים ומופעים, 3 אחר. פלטינום: 6/6/6. לא ניתן לצבור — המכסה מתאפסת כל חודש.",
    shareability: "personal_only",
    source_url: "https://www.pais.co.il/info/default.aspx?PageId=1178",
  },

  // ------------------------------------------------------------ משרתי מילואים
  {
    seed_key: "miluim-tax-credit",
    program_slug: "miluim",
    title_he: "נקודות זיכוי במס הכנסה",
    merchant: "רשות המסים",
    category: "finance",
    discount_text: "זיכוי במס לפי ימי השירות",
    description_he:
      "מחושב לפי השירות של החייל עצמו. זכות אישית שלא ניתן להעביר לאף אחד.",
    shareability: "personal_only",
    source_url:
      "https://www.kolzchut.org.il/he/%D7%A0%D7%A7%D7%95%D7%93%D7%95%D7%AA_%D7%96%D7%99%D7%9B%D7%95%D7%99_%D7%9E%D7%9E%D7%A1_%D7%94%D7%9B%D7%A0%D7%A1%D7%94_%D7%9C%D7%9C%D7%95%D7%97%D7%9E%D7%99_%D7%9E%D7%99%D7%9C%D7%95%D7%90%D7%99%D7%9D",
  },
  {
    seed_key: "miluim-family-grant",
    program_slug: "miluim",
    title_he: "מענק משפחה מוגדל",
    merchant: "משרד הביטחון",
    category: "finance",
    discount_text: "מענק למשרתים עם ילדים",
    description_he:
      "למשרתים שביצעו לפחות 40 ימי שירות בשנה ויש להם ילד עד גיל 14. משולם ישירות למשרת.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-employment-grant",
    program_slug: "miluim",
    title_he: "מענקי תעסוקה וחזרה ללימודים",
    merchant: "משרד האוצר",
    category: "finance",
    discount_text: "מענקים משלימים",
    description_he: "סיוע לחיילים החוזרים ללימודים ולשוק העבודה.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-self-employed",
    program_slug: "miluim",
    title_he: "סיוע לעצמאים ובעלי עסקים",
    merchant: "משרד האוצר",
    category: "finance",
    discount_text: "סיוע כלכלי לעסק",
    description_he: "סיוע לעצמאים שנפגעו כלכלית עקב השירות.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-family-support",
    program_slug: "miluim",
    title_he: "סיוע למשפחות, הורים וסטודנטים",
    merchant: "משרד הביטחון",
    category: "finance",
    discount_text: "סל סיוע ייעודי",
    description_he: null,
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-business-discounts",
    program_slug: "miluim",
    title_he: "הנחות בבתי עסק למשרתי מילואים",
    merchant: "בתי עסק ורשתות משתתפים",
    category: "other",
    discount_text: "הנחה בהצגת תעודה",
    description_he:
      "ניתן בהצגת תעודת משרת מילואים, ולכן החבר עצמו צריך להיות שם.",
    shareability: "presence_required",
    source_url: "https://www.miluim.idf.il/",
  },
  {
    seed_key: "miluim-active-status",
    program_slug: "miluim",
    title_he: "מעמד משרת מילואים פעיל",
    merchant: "צה״ל",
    category: "other",
    discount_text: "פותח זכאות להטבות נוספות",
    description_he:
      "המעמד עצמו הוא תנאי סף להטבות רבות. אישי לחלוטין.",
    shareability: "personal_only",
    source_url: "https://www.miluim.idf.il/",
  },

  // ------------------------------------------------------ American Express IL
  {
    seed_key: "amex-membership-rewards",
    program_slug: "amex-il",
    title_he: "Membership Rewards — צבירת נקודות",
    merchant: "American Express",
    category: "finance",
    discount_text: "נקודות על כל עסקה",
    description_he: "הנקודות נצברות לחשבון של בעל הכרטיס בלבד.",
    shareability: "personal_only",
    source_url: "https://he.americanexpress.co.il/membership-rewards1/",
  },
  {
    seed_key: "amex-rewards-culture",
    program_slug: "amex-il",
    title_he: "אתר ההטבות — תרבות ופנאי",
    merchant: "מופעים, הצגות ואטרקציות",
    category: "culture",
    discount_text: "מחירי מועדון",
    description_he: "הזמנה דרך אתר ההטבות; את הכרטיס אפשר להעביר.",
    shareability: "transferable",
    source_url: "https://rewards.americanexpress.co.il/",
  },
  {
    seed_key: "amex-rewards-travel",
    program_slug: "amex-il",
    title_he: "אתר ההטבות — נופש וחו״ל",
    merchant: "מלונות, טיסות וחבילות נופש",
    category: "travel",
    discount_text: "מחירי מועדון",
    description_he: null,
    shareability: "transferable",
    source_url: "https://rewards.americanexpress.co.il/",
  },
  {
    seed_key: "amex-lifestyle",
    program_slug: "amex-il",
    title_he: "מועדון LifeStyle — הנחות אוטומטיות",
    merchant: "למעלה מ-3,000 בתי עסק",
    category: "other",
    discount_text: "הנחה במעמד החיוב",
    description_he:
      "ההנחה נכנסת אוטומטית בחיוב החשבון, ולכן דורשת את הכרטיס של החבר.",
    shareability: "presence_required",
    source_url: "https://he.americanexpress.co.il/style/",
  },
  {
    seed_key: "amex-lifestyle-chains",
    program_slug: "amex-il",
    title_he: "הנחות ברשתות המועדון",
    merchant: "סופר-פארם, מקדונלד׳ס, סטימצקי, איסתא",
    category: "food",
    discount_text: "הנחות קבועות",
    description_he: "רשתות קבועות של מועדון LifeStyle.",
    shareability: "presence_required",
    source_url: "https://he.americanexpress.co.il/style/",
  },
  {
    seed_key: "amex-hot-card-fx",
    program_slug: "amex-il",
    title_he: "כרטיס מועדון הוט — עמלת מט״ח מוזלת",
    merchant: "American Express",
    category: "finance",
    discount_text: "1% על רכישות בחו״ל",
    description_he: "תנאי של הכרטיס האישי, כולל רכישות באתרים בינלאומיים.",
    shareability: "personal_only",
    source_url: "https://marketing.americanexpress.co.il/cards-clubs/hot/",
  },
  {
    seed_key: "amex-hot-card-network",
    program_slug: "amex-il",
    title_he: "הנחות בכ-13,000 בתי עסק (כרטיס הוט)",
    merchant: "מזון, דלק, תיירות, חשמל ואופנה",
    category: "other",
    discount_text: "הנחה אוטומטית",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://marketing.americanexpress.co.il/cards-clubs/hot/",
  },
  {
    seed_key: "amex-hever",
    program_slug: "amex-il",
    title_he: "כרטיס מועדון חבר",
    merchant: "אלפי רשתות ובתי עסק",
    category: "other",
    discount_text: "הנחות בכל קנייה",
    description_he: "מיועד לחברי מועדון חבר — משרתי קבע וגמלאי צה״ל.",
    shareability: "presence_required",
    source_url: "https://www.americanexpress.co.il/credit-cards/hevercard",
  },
];
