/**
 * Starter catalog.
 *
 * Every row here is a *standing* benefit that the program documents publicly on
 * its own site, and each carries the source_url it came from. Time-limited
 * merchant promotions deliberately are NOT seeded: they live behind member
 * logins and mobile apps, they change weekly, and inventing plausible-looking
 * ones would be worse than an empty feed. Those come from members through the
 * quick-add form.
 *
 * Seed rows are global (group_id NULL) and authorless (created_by NULL), which
 * is what distinguishes them from member contributions. `seed_key` is their
 * stable identity for upserts.
 *
 * verified_at is deliberately left NULL: these were read off public marketing
 * pages, not confirmed inside a member account. The first member to check one
 * can stamp it.
 */
import type { OfferCategory, Shareability } from "../../lib/types";

export interface SeedOffer {
  seed_key: string;
  program_slug: string;
  title_he: string;
  merchant: string;
  category: OfferCategory;
  discount_text: string;
  description_he: string | null;
  shareability: Shareability;
  source_url: string;
}

export const OFFERS: SeedOffer[] = [
  // ---------------------------------------------------------------- לאומי בונוס
  {
    seed_key: "leumi-bonus-food-vouchers",
    program_slug: "leumi-bonus",
    title_he: "תווי בונוס לרשתות מזון ופארם",
    merchant: "רשתות מזון ופארם",
    category: "food",
    discount_text: "עד 20% חזרה מהבנק",
    description_he:
      "רוכשים תו בסכום שבוחרים, והבנק מחזיר חלק מהסכום לחשבון. את התו עצמו אפשר להעביר.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/category/1329",
  },
  {
    seed_key: "leumi-bonus-checkout-discounts",
    program_slug: "leumi-bonus",
    title_he: "הנחות קבועות במעמד החיוב",
    merchant: "רשתות ובתי עסק מובילים",
    category: "other",
    discount_text: "הנחה אוטומטית בחיוב",
    description_he:
      "ההנחה נכנסת אוטומטית כשמשלמים בכרטיס לאומי, ולכן צריך שבעל הכרטיס יהיה זה שמשלם.",
    shareability: "presence_required",
    source_url: "https://www.leumi.co.il/he/bonus",
  },
  {
    seed_key: "leumi-bonus-fx-fee",
    program_slug: "leumi-bonus",
    title_he: "עמלת עסקאות מט״ח מוזלת",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "1.5% בלבד",
    description_he: "תנאי של הכרטיס עצמו — חל רק על העסקאות של בעל הכרטיס.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/he/credit-cards",
  },
  {
    seed_key: "leumi-bonus-shopping-vouchers",
    program_slug: "leumi-bonus",
    title_he: "תווי קנייה למותגים ורשתות",
    merchant: "מותגי אופנה, חשמל ובית",
    category: "fashion",
    discount_text: "תווי קנייה בהנחה",
    description_he: "תו קנייה שנרכש דרך המועדון ניתן להעברה למי שישתמש בו.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/",
  },
  {
    seed_key: "leumi-bonus-leisure",
    program_slug: "leumi-bonus",
    title_he: "מבלים ונהנים — מסעדות, מופעים ואטרקציות",
    merchant: "מסעדות, מופעים ואטרקציות",
    category: "culture",
    discount_text: "מחירים מוזלים למחזיקי הכרטיס",
    description_he: "קטגוריית הפנאי של לאומי בונוס: הצגות, אטרקציות למשפחה ומסעדות.",
    shareability: "transferable",
    source_url: "https://bonus.leumi.co.il/category/1349",
  },
  {
    seed_key: "leumi-bonus-servicemen",
    program_slug: "leumi-bonus",
    title_he: "הטבות למשרתים",
    merchant: "בנק לאומי",
    category: "other",
    discount_text: "מסלול הטבות ייעודי",
    description_he: "קטגוריית הטבות ייעודית למשרתי מילואים ומשרתי כוחות הביטחון.",
    shareability: "presence_required",
    source_url: "https://bonus.leumi.co.il/category/1627",
  },
  {
    seed_key: "leumi-bonus-new-account",
    program_slug: "leumi-bonus",
    title_he: "הטבות פתיחת חשבון",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "מסלול הטבות למצטרפים",
    description_he: "רלוונטי למי שפותח חשבון בעצמו — לא ניתן להעברה.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/open-account/",
  },

  // --------------------------------------------------------- מועדון צרכנות HOT
  {
    seed_key: "hot-14k-businesses",
    program_slug: "hot-club",
    title_he: "הנחות בכ-14,000 בתי עסק",
    merchant: "רשתות ובתי עסק בכל הארץ",
    category: "other",
    discount_text: "הנחה במעמד החיוב",
    description_he:
      "ההנחה מוצמדת לכרטיס המועדון, ולכן החבר עצמו צריך לשלם או להיות בקופה.",
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-digital-wallet",
    program_slug: "hot-club",
    title_he: "ארנק דיגיטלי — שוברים למותגים",
    merchant: "מותגי אופנה, בית, ספורט וטיפוח",
    category: "fashion",
    discount_text: "עד 20% הנחה",
    description_he:
      "שוברים דיגיטליים למותגים, כלי בית, צעצועים, ריהוט, מסעדות ובתי קפה. השובר עובר בקלות.",
    shareability: "transferable",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-supermarkets",
    program_slug: "hot-club",
    title_he: "הנחות ברשתות המזון",
    merchant: "רשתות מזון",
    category: "food",
    discount_text: "הנחה קבועה בקופה",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-travel",
    program_slug: "hot-club",
    title_he: "הטבות תיירות ונופש",
    merchant: "חברות תיירות ומלונות",
    category: "travel",
    discount_text: "מחירי מועדון",
    description_he: "הזמנה שמבצע החבר עבור מי שנוסע — לרוב ניתנת להעברה.",
    shareability: "transferable",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-electronics",
    program_slug: "hot-club",
    title_he: "הנחות בחשמל ומוצרים לבית",
    merchant: "רשתות חשמל ומוצרי בית",
    category: "electronics",
    discount_text: "הנחת מועדון",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://www.hot.co.il/",
  },
  {
    seed_key: "hot-card-fee-waiver",
    program_slug: "hot-club",
    title_he: "פטור מדמי כרטיס אשראי",
    merchant: "מועדון הוט",
    category: "finance",
    discount_text: "ללא דמי כרטיס",
    description_he: "תנאי של הכרטיס האישי — לא רלוונטי לאף אחד אחר.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/hot_consumer_card/",
  },
  {
    seed_key: "hot-loan",
    program_slug: "hot-club",
    title_he: "הלוואה לכל מטרה בתנאי מועדון",
    merchant: "בנק לאומי",
    category: "finance",
    discount_text: "עד 160,000 ₪",
    description_he: "הלוואה בתנאים מיוחדים לחברי מועדון הוט. אישית לחלוטין.",
    shareability: "personal_only",
    source_url: "https://www.leumi.co.il/minisite/hot_consumer_card/",
  },
  {
    seed_key: "hot-insurance",
    program_slug: "hot-club",
    title_he: "הטבות בביטוח ובפיננסים",
    merchant: "חברות ביטוח ופיננסים",
    category: "finance",
    discount_text: "תנאי מועדון",
    description_he: null,
    shareability: "personal_only",
    source_url: "https://www.hot.co.il/",
  },

  // ------------------------------------------------------------------ פיס פלוס
  {
    seed_key: "pais-theatre",
    program_slug: "pais-plus",
    title_he: "כרטיסים להצגות",
    merchant: "תיאטראות והיכלי תרבות",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he:
      "המנוי מזמין דרך החשבון שלו ומעביר את הכרטיס — ההטבה הכי נוחה לשיתוף.",
    shareability: "transferable",
    source_url: "https://paisplus.co.il/category/291",
  },
  {
    seed_key: "pais-shows",
    program_slug: "pais-plus",
    title_he: "מופעי מוסיקה והופעות",
    merchant: "אולמות ואמפיתיאטרונים",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/category/282",
  },
  {
    seed_key: "pais-movies",
    program_slug: "pais-plus",
    title_he: "כרטיסים לסרטים",
    merchant: "רשתות בתי הקולנוע",
    category: "culture",
    discount_text: "כרטיסים בהנחה",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/category/152",
  },
  {
    seed_key: "pais-standup",
    program_slug: "pais-plus",
    title_he: "מופעי סטנד אפ",
    merchant: "מועדוני סטנד אפ",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-museums",
    program_slug: "pais-plus",
    title_he: "מוזיאונים ותערוכות",
    merchant: "מוזיאונים ברחבי הארץ",
    category: "culture",
    discount_text: "כניסה מוזלת",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-family",
    program_slug: "pais-plus",
    title_he: "מופעים לכל המשפחה",
    merchant: "היכלי תרבות ואמפיתיאטרונים",
    category: "culture",
    discount_text: "מחיר מנויים",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-restaurants",
    program_slug: "pais-plus",
    title_he: "הטבות במסעדות",
    merchant: "מסעדות ובתי קפה",
    category: "food",
    discount_text: "הנחות למנויים",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/",
  },
  {
    seed_key: "pais-live-festival",
    program_slug: "pais-plus",
    title_he: "פסטיבל פיס LIVE",
    merchant: "מפעל הפיס",
    category: "culture",
    discount_text: "בלעדי למנויי הפיס",
    description_he: "פסטיבל שמיועד למנויים בלבד. המנוי מזמין ומעביר כרטיסים.",
    shareability: "transferable",
    source_url: "https://www.pais.co.il/info/paisplus.aspx",
  },
  {
    seed_key: "pais-vip",
    program_slug: "pais-plus",
    title_he: "הטבות VIP לפלטינום וגולד+",
    merchant: "מפעל הפיס",
    category: "other",
    discount_text: "הטבות בלעדיות לפי דרגה",
    description_he: "תלוי בדרגת המנוי של החבר עצמו.",
    shareability: "personal_only",
    source_url: "https://www.pais.co.il/info/paisplus.aspx",
  },
  {
    seed_key: "pais-vacation",
    program_slug: "pais-plus",
    title_he: "הטבות נופש וחופשות",
    merchant: "מלונות ואתרי נופש",
    category: "travel",
    discount_text: "מחירי מנויים",
    description_he: null,
    shareability: "transferable",
    source_url: "https://paisplus.co.il/",
  },

  // ------------------------------------------------------------ משרתי מילואים
  {
    seed_key: "miluim-tax-credit",
    program_slug: "miluim",
    title_he: "נקודות זיכוי במס הכנסה",
    merchant: "רשות המסים",
    category: "finance",
    discount_text: "זיכוי במס לפי ימי השירות",
    description_he:
      "מחושב לפי השירות של החייל עצמו. זכות אישית שלא ניתן להעביר לאף אחד.",
    shareability: "personal_only",
    source_url:
      "https://www.kolzchut.org.il/he/%D7%A0%D7%A7%D7%95%D7%93%D7%95%D7%AA_%D7%96%D7%99%D7%9B%D7%95%D7%99_%D7%9E%D7%9E%D7%A1_%D7%94%D7%9B%D7%A0%D7%A1%D7%94_%D7%9C%D7%9C%D7%95%D7%97%D7%9E%D7%99_%D7%9E%D7%99%D7%9C%D7%95%D7%90%D7%99%D7%9D",
  },
  {
    seed_key: "miluim-family-grant",
    program_slug: "miluim",
    title_he: "מענק משפחה מוגדל",
    merchant: "משרד הביטחון",
    category: "finance",
    discount_text: "מענק למשרתים עם ילדים",
    description_he:
      "למשרתים שביצעו לפחות 40 ימי שירות בשנה ויש להם ילד עד גיל 14. משולם ישירות למשרת.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-employment-grant",
    program_slug: "miluim",
    title_he: "מענקי תעסוקה וחזרה ללימודים",
    merchant: "משרד האוצר",
    category: "finance",
    discount_text: "מענקים משלימים",
    description_he: "סיוע לחיילים החוזרים ללימודים ולשוק העבודה.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-self-employed",
    program_slug: "miluim",
    title_he: "סיוע לעצמאים ובעלי עסקים",
    merchant: "משרד האוצר",
    category: "finance",
    discount_text: "סיוע כלכלי לעסק",
    description_he: "סיוע לעצמאים שנפגעו כלכלית עקב השירות.",
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-family-support",
    program_slug: "miluim",
    title_he: "סיוע למשפחות, הורים וסטודנטים",
    merchant: "משרד הביטחון",
    category: "finance",
    discount_text: "סל סיוע ייעודי",
    description_he: null,
    shareability: "personal_only",
    source_url: "https://www.matzdiim.co.il/",
  },
  {
    seed_key: "miluim-business-discounts",
    program_slug: "miluim",
    title_he: "הנחות בבתי עסק למשרתי מילואים",
    merchant: "בתי עסק ורשתות משתתפים",
    category: "other",
    discount_text: "הנחה בהצגת תעודה",
    description_he:
      "ניתן בהצגת תעודת משרת מילואים, ולכן החבר עצמו צריך להיות שם.",
    shareability: "presence_required",
    source_url: "https://www.miluim.idf.il/",
  },
  {
    seed_key: "miluim-active-status",
    program_slug: "miluim",
    title_he: "מעמד משרת מילואים פעיל",
    merchant: "צה״ל",
    category: "other",
    discount_text: "פותח זכאות להטבות נוספות",
    description_he:
      "המעמד עצמו הוא תנאי סף להטבות רבות. אישי לחלוטין.",
    shareability: "personal_only",
    source_url: "https://www.miluim.idf.il/",
  },

  // ------------------------------------------------------ American Express IL
  {
    seed_key: "amex-membership-rewards",
    program_slug: "amex-il",
    title_he: "Membership Rewards — צבירת נקודות",
    merchant: "American Express",
    category: "finance",
    discount_text: "נקודות על כל עסקה",
    description_he: "הנקודות נצברות לחשבון של בעל הכרטיס בלבד.",
    shareability: "personal_only",
    source_url: "https://he.americanexpress.co.il/membership-rewards1/",
  },
  {
    seed_key: "amex-rewards-culture",
    program_slug: "amex-il",
    title_he: "אתר ההטבות — תרבות ופנאי",
    merchant: "מופעים, הצגות ואטרקציות",
    category: "culture",
    discount_text: "מחירי מועדון",
    description_he: "הזמנה דרך אתר ההטבות; את הכרטיס אפשר להעביר.",
    shareability: "transferable",
    source_url: "https://rewards.americanexpress.co.il/",
  },
  {
    seed_key: "amex-rewards-travel",
    program_slug: "amex-il",
    title_he: "אתר ההטבות — נופש וחו״ל",
    merchant: "מלונות, טיסות וחבילות נופש",
    category: "travel",
    discount_text: "מחירי מועדון",
    description_he: null,
    shareability: "transferable",
    source_url: "https://rewards.americanexpress.co.il/",
  },
  {
    seed_key: "amex-lifestyle",
    program_slug: "amex-il",
    title_he: "מועדון LifeStyle — הנחות אוטומטיות",
    merchant: "למעלה מ-3,000 בתי עסק",
    category: "other",
    discount_text: "הנחה במעמד החיוב",
    description_he:
      "ההנחה נכנסת אוטומטית בחיוב החשבון, ולכן דורשת את הכרטיס של החבר.",
    shareability: "presence_required",
    source_url: "https://he.americanexpress.co.il/style/",
  },
  {
    seed_key: "amex-lifestyle-chains",
    program_slug: "amex-il",
    title_he: "הנחות ברשתות המועדון",
    merchant: "סופר-פארם, מקדונלד׳ס, סטימצקי, איסתא",
    category: "food",
    discount_text: "הנחות קבועות",
    description_he: "רשתות קבועות של מועדון LifeStyle.",
    shareability: "presence_required",
    source_url: "https://he.americanexpress.co.il/style/",
  },
  {
    seed_key: "amex-hot-card-fx",
    program_slug: "amex-il",
    title_he: "כרטיס מועדון הוט — עמלת מט״ח מוזלת",
    merchant: "American Express",
    category: "finance",
    discount_text: "1% על רכישות בחו״ל",
    description_he: "תנאי של הכרטיס האישי, כולל רכישות באתרים בינלאומיים.",
    shareability: "personal_only",
    source_url: "https://marketing.americanexpress.co.il/cards-clubs/hot/",
  },
  {
    seed_key: "amex-hot-card-network",
    program_slug: "amex-il",
    title_he: "הנחות בכ-13,000 בתי עסק (כרטיס הוט)",
    merchant: "מזון, דלק, תיירות, חשמל ואופנה",
    category: "other",
    discount_text: "הנחה אוטומטית",
    description_he: null,
    shareability: "presence_required",
    source_url: "https://marketing.americanexpress.co.il/cards-clubs/hot/",
  },
  {
    seed_key: "amex-hever",
    program_slug: "amex-il",
    title_he: "כרטיס מועדון חבר",
    merchant: "אלפי רשתות ובתי עסק",
    category: "other",
    discount_text: "הנחות בכל קנייה",
    description_he: "מיועד לחברי מועדון חבר — משרתי קבע וגמלאי צה״ל.",
    shareability: "presence_required",
    source_url: "https://www.americanexpress.co.il/credit-cards/hevercard",
  },
];
